### ISSUE TITLE
Add dark theme 

### ISSUE THREAD

**Issue by yacut** [kafka-owl/kafka-owl#4]
I prefer dark theme. Could you please add it?

**Comment by rikimaru0345** [comment]
Would this be ok?
https://github.com/ant-design/ant-design-dark-theme

I can probably add it later today.

**Comment by rikimaru0345** [comment]
It seems like `ant-design-dark-theme` would work well with a standard ant-design theme, but we've got some stuff built on the light theme already.

All the inline styles that are currently causing problems when using ant-design-dark-theme will be removed/cleaned up eventually.
That's when I'll look into this again.

If you want to do it, uncomment those lines :smile: : https://github.com/kafka-owl/kafka-owl/blob/2b816fd8fac240280e3b2a21ecc8b8c84757dd9a/frontend/config-overrides.js#L23-L26
