### ISSUE TITLE
Add build pipeline

### ISSUE THREAD

**Issue by weeco** [kafka-owl/kafka-owl#7]
We should create a pipeline which builds and potentially tests our containers. Upon creating a release we should also release that docker image into the package registry. Since we are activated for GitHub actions + package registry I suggest to use both.

**Comment by rikimaru0345** [comment]
The action/workflow thing here works: https://github.com/kafka-owl/actions-test/blob/riki-test/.github/workflows/riki.yml

I'll take care of the docker image build, push, showing the version in the frontend, etc tomorrow (if it isn't already done).

**Comment by rikimaru0345** [comment]
Implemented with https://github.com/kafka-owl/kafka-owl/commit/3cdff066c4e9bab25ee4ad34ec7e965c7b16b109
